src/main/java/com/example/fishingstore/domain/ListOrder.java
package com.example.fishingstore.domain;

public class ListOrder {
    private long id;
    private String username;
    private boolean active;

    public ListOrder(long id, String username, boolean active) {
        this.id = id;
        this.username = username;
        this.active = active;
    }

    public ListOrder() {
    }

    public long getId_ord() {
        return id;
    }

    public void setId_ord(long id) {
        this.id = id;
    }

    public String getName() {
        return username;
    }

    public void setName(String username) {
        this.username = username;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    @Override
    public String toString() {
        return "ListOrder{" +
                "id_ord=" + id +
                 ", username='" + username +
                ", active=" + active +
                '}';
    }
}

src/main/resources/templates/productsUser/addHookToOrder.ftl
<#import "../parts/common.ftl" as c>
<#include "../parts/security.ftl">
<@c.page>
    Add hook to order
    <form action="/hooksUser" method="post">
        Name:${hook.name} <br>
        <input type="hidden" value="${hook.id}" name="id">
        <input type="hidden" value="${customer_id}" name="customer_id">

        Manufacturer: ${hook.manufacturer} <br/>
        Size :${hook.size?string("0.##")} <br/>
        Price:${hook.price?string("0.##")}<br/>
        <input type="hidden" value="${hook.price?string("0.##")}" name="price"/>
        <input type="text" class="form-control" name="amount" placeholder="Amount"/>


        <input type="hidden" value="${_csrf.token}" name="_csrf">
        <button type="submit"> Add to order</button>
    </form>

</@c.page>

src/main/resources/templates/productsUser/addLineToOrder.ftl
<#import "../parts/common.ftl" as c>
<#include "../parts/security.ftl">
<@c.page>
    Add line to order
    <form action="/linesUser" method="post">
        Name:${line.name}    <br>
        <input type="hidden" value="${line.id}" name="id">
        <input type="hidden" value="${customer_id}" name="customer_id">

        Manufacturer: ${line.manufacturer} <br>
        Length: ${line.length?string("0.##")} <br>
        Diameter:${line.diameter?string("0.##")} <br>
        Price:${line.price?string("0.##")} <br>
        <input type="hidden" value="${line.price?string("0.##")}" name="price"/>
        <input type="text" class="form-control" name="amount" placeholder="Amount"/>


        <input type="hidden" value="${_csrf.token}" name="_csrf">
        <button type="submit"> Add to order</button>
    </form>

</@c.page>

src/main/resources/templates/productsUser/addReelToOrder.ftl
<#import "../parts/common.ftl" as c>
<#include "../parts/security.ftl">
<@c.page>
    Add reel to order
    <form action="/reelsUser" method="post">
        Name:${reel.name}    <br>
        <input type="hidden" value="${reel.id}" name="id">
        <input type="hidden" value="${customer_id}" name="customer_id">

        Manufacturer: ${reel.manufacturer} <br>
        Amount of balls:${reel.amount_balls?string("0.##")} <br>
        Price:${reel.price?string("0.##")} <br>
        <input type="hidden" value="${reel.price?string("0.##")}" name="price"/>
        <input type="text" class="form-control" name="amount" placeholder="Amount"/>


        <input type="hidden" value="${_csrf.token}" name="_csrf">
        <button type="submit"> Add to order</button>
    </form>

</@c.page>

src/main/resources/templates/productsUser/addRodToOrder.ftl
<#import "../parts/common.ftl" as c>
<#include "../parts/security.ftl">
<@c.page>
    Add rod to order
    <form action="/rodsUser" method="post">
        Name:${rod.name}    <br>
        <input type="hidden" value="${rod.id}" name="id">
        <input type="hidden" value="${customer_id}" name="customer_id">
        Manufacturer: ${rod.manufacturer} <br>
        Length: ${rod.length?string("0.##")} <br>
        Test max:${rod.testMax?string("0.##")} <br>
        Test min:${rod.testMin?string("0.##")} <br>
        Price:${rod.price?string("0.##")} <br>
        <input type="text" class="form-control" name="amount" placeholder="Amount"/>
        <input type="hidden" value="${rod.price?string("0.##")}" name="price"/>

        <input type="hidden" value="${_csrf.token}" name="_csrf">
        <button type="submit"> Add to order</button>
    </form>

</@c.page>

src/main/resources/templates/productsUser/editForm.ftl
<#import "../parts/common.ftl" as c>
<#include "../parts/security.ftl">
<@c.page>
    Add hook to order
    <form action="/hooksUser" method="post">
        <input type="hidden" value="${_csrf.token}" name="_csrf">
        <input type="hidden" value="${hook.id}">
        Type : "${hook.type}" <br/>
        Name Product : "${hook.name_product}" <br/>
        Price: "${hook.price}" <br/>
        Amount: <input type="text" name="amount"
                       value="<c:out value="${hookCart.amount}" />"/> <br/>

        <input type="hidden" value="${_csrf.token}" name="_csrf">
        <button type="submit"> Add to order</button>
    </form>

</@c.page>

src/main/resources/templates/productsUser/hooksforUser.ftl
<#import "../parts/common.ftl" as c>

<@c.page>
    <div class="form-row">
        <div class="form-group col-md-6">
            <form method="get" action="/hooksUser" class="form-inline">
                <input type="text" name="filter" class="form-control" value="${filter?ifExists}"
                       placeholder="Search by name hook">
                <button type="submit" class="btn btn-primary ml-2">Search</button>
            </form>
        </div>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Size</th>
            <th scope="col">Price</th>
            <th scope="col">Action
            <th>
        </tr>
        </thead>
        <tbody>
        <#list hooks as hook>
            <tr>
                <th>${hook.name}</th>
                <th>${hook.manufacturer}</th>
                <th>${hook.size}</th>
                <th>${hook.price}</th>
                <td><a href="/hooksUser/${hook.id}">Add to order</a></td>
            </tr>
        <#else>
            No hook
        </#list>
        </tbody>
    </table>

</@c.page>

src/main/resources/templates/productsUser/linesforUser.ftl
<#import "../parts/common.ftl" as c>

<@c.page>
    <div class="form-row">
        <div class="form-group col-md-6">
            <form method="get" action="/linesUser" class="form-inline">
                <input type="text" name="filter" class="form-control" value="${filter?ifExists}"
                       placeholder="Search by name line">
                <button type="submit" class="btn btn-primary ml-2">Search</button>
            </form>
        </div>
    </div>

    <table class="table">

        <thead>

        <tr>
            <th scope="col">Name</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Length</th>
            <th scope="col">Diameter</th>
            <th scope="col">Price</th>
             <th scope="col">Action<th>
        </tr>
        </thead>
        <tbody>
        <#list lines as line>
            <tr>
                <th>${line.name}</th>
                <th>${line.manufacturer}</th>
                <th>${line.length}</th>
                <th>${line.diameter}</th>
                <th>${line.price}</th>
                 <td><a href="/linesUser/${line.id}">Add to order</a></td>
            </tr>

        <#else>
            No line
        </#list>

        </tbody>
    </table>

</@c.page>

src/main/resources/templates/productsUser/reelsforUser.ftl
<#import "../parts/common.ftl" as c>

<@c.page>
    <div class="form-row">
        <div class="form-group col-md-6">
            <form method="get" action="/reelsUser" class="form-inline">
                <input type="text" name="filter" class="form-control" value="${filter?ifExists}"
                       placeholder="Search by name line">
                <button type="submit" class="btn btn-primary ml-2">Search</button>
            </form>
        </div>
    </div>

    <table class="table">
        <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Amount of balls</th>
            <th scope="col">Price</th>
            <th scope="col">Action
            <th>
        </tr>
        </thead>
        <tbody>
        <#list reels as reel>
            <tr>
                <th>${reel.name}</th>
                <th>${reel.manufacturer}</th>
                <th>${reel.amount_balls}</th>
                <th>${reel.price}</th>
                <td><a href="/reelsUser/${reel.id}">Add to order</a></td>
            </tr>
        <#else>
            No reel
        </#list>
        </tbody>
    </table>

</@c.page>

src/main/resources/templates/productsUser/rodsforUser.ftl
<#import "../parts/common.ftl" as c>

<@c.page>
    <div class="form-row">
        <div class="form-group col-md-6">
            <form method="get" action="/rodsUser" class="form-inline">
                <input type="text" name="filter" class="form-control" value="${filter?ifExists}"
                       placeholder="Search by name line">
                <button type="submit" class="btn btn-primary ml-2">Search</button>
            </form>
        </div>
    </div>

    <table class="table">

        <thead>

        <tr>
            <th scope="col">Name</th>
            <th scope="col">Manufacturer</th>
            <th scope="col">Length</th>
            <th scope="col">Test max</th>
            <th scope="col">Test min</th>
            <th scope="col">Price</th>
             <th scope="col">Action<th>
        </tr>
        </thead>
        <tbody>
        <#list rods as rod>
            <tr>
                <th>${rod.name}</th>
                <th>${rod.manufacturer}</th>
                <th>${rod.length}</th>
                <th>${rod.testMax}</th>
                <th>${rod.testMin}</th>
                <th>${rod.price}</th>
                 <td><a href="/rodsUser/${rod.id}">Add to order</a></td>
            </tr>

        <#else>
            No rod
        </#list>

        </tbody>
    </table>

</@c.page>